[build]
buildCommand = "cd backend && npm ci && npx prisma generate && npx prisma migrate deploy"

[deploy]
startCommand = "cd backend && node src/index.js"

[env]
NODE_ENV = "production"
FORCE_REBUILD = "2025-08-17-v2"