[build]
buildCommand = "rm -rf backend/node_modules && cd backend && npm install && npx prisma generate && npx prisma migrate deploy && psql $DATABASE_URL -f create-employee-user.sql"

[deploy]
startCommand = "cd backend && node src/index.js"

[deploy.healthcheckPath]
path = "/health"

[env]
NODE_ENV = "production"
FORCE_REBUILD = "2025-08-17-v3"